# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ScqpuDqQEtlsczaMEKxQN4zxiRTTSEUv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import pickle

data = pd.read_excel("Bank_Personal_Loan_Modelling.xlsx")

data.head(5)

data.tail(5)

data.isnull().sum()

data["Personal Loan"].value_counts()

data.set_index(data["ID"],inplace=True)

data=data.drop(["ID","ZIP Code"],axis=1)

data.head(3)

data.dtypes

from sklearn.model_selection import train_test_split

data['Personal Loan']=data['Personal Loan'].astype('category')
y=data["Personal Loan"]
x=data.drop("Personal Loan",axis=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

lr=LogisticRegression()

lr.fit(x_train,y_train)

train_pred=lr.predict(x_train)
test_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_train,train_pred)

accuracy_score(y_test,test_pred)

from sklearn.tree import DecisionTreeClassifier

dtc =DecisionTreeClassifier()

dtc.fit(x_train,y_train)

train_pred_dtc=dtc.predict(x_train)
test_pred_dtc=dtc.predict(x_test)

accuracy_score(y_train,train_pred_dtc)

accuracy_score(y_test,test_pred_dtc)

pickle.dump(lr, open('model.pkl','wb'))
model = pickle.load(open('model.pkl','rb'))

x_train

